### ISSUE TITLE
CUDA graph error when running Apptronik Apollo Locomotion notebook

### ISSUE THREAD

**Issue by HaoliangWang** [google-deepmind/mujoco_warp#552]
I was trying to run [the Apptronik Apollo Locomotion notebook](https://github.com/google-deepmind/mujoco_warp/blob/main/contrib/apptronik_apollo_locomotion.ipynb) provided in this repo. However, when I run this line:

```
make_inference_fn, params, metrics = train_fn(
  environment=env,
  wrap_env_fn=wrapper.wrap_for_brax_training,
)
```

It gave me the error saying:

```
---------------------------------------------------------------------------
XlaRuntimeError                           Traceback (most recent call last)
Cell In[5], [line 71](vscode-notebook-cell:?execution_count=5&line=71)
     62 train_fn = functools.partial(
     63   ppo.train,
     64   **dict(ppo_training_params),
     65   network_factory=network_factory,
     66   progress_fn=progress,
     67 )
     69 env = Joystick()
---> [71](vscode-notebook-cell:?execution_count=5&line=71) make_inference_fn, params, metrics = train_fn(
     72   environment=env,
     73   wrap_env_fn=wrapper.wrap_for_brax_training,
     74 )
     76 print(f"time to jit: {times[1] - times[0]}")
     77 print(f"time to train: {times[-1] - times[1]}")

File ~/.conda/envs/mjwarp/lib/python3.12/site-packages/brax/training/agents/ppo/train.py:675, in train(environment, num_timesteps, max_devices_per_host, wrap_env, madrona_backend, augment_pixels, num_envs, episode_length, action_repeat, wrap_env_fn, randomization_fn, learning_rate, entropy_cost, discounting, unroll_length, batch_size, num_minibatches, num_updates_per_batch, num_resets_per_eval, normalize_observations, reward_scaling, clipping_epsilon, gae_lambda, max_grad_norm, normalize_advantage, network_factory, seed, num_evals, eval_env, num_eval_envs, deterministic_eval, log_training_metrics, training_metrics_steps, progress_fn, policy_params_fn, save_checkpoint_path, restore_checkpoint_path, restore_params, restore_value_fn, run_evals)
    673 metrics = {}
    674 if process_id == 0 and num_evals > 1 and run_evals:
--> [675](https://vscode-remote+ssh-002dremote-002borcd-002dcompute.vscode-resource.vscode-cdn.net/home/hlwang/code/mujoco_warp/contrib/~/.conda/envs/mjwarp/lib/python3.12/site-packages/brax/training/agents/ppo/train.py:675)   metrics = evaluator.run_evaluation(
    676       _unpmap((
    677           training_state.normalizer_params,
    678           training_state.params.policy,
    679           training_state.params.value,
    680       )),
    681       training_metrics={},
    682   )
    683   logging.info(metrics)
    684   progress_fn(0, metrics)

File ~/.conda/envs/mjwarp/lib/python3.12/site-packages/brax/training/acting.py:133, in Evaluator.run_evaluation(self, policy_params, training_metrics, aggregate_episodes)
    130 self._key, unroll_key = jax.random.split(self._key)
    132 t = time.time()
--> [133](https://vscode-remote+ssh-002dremote-002borcd-002dcompute.vscode-resource.vscode-cdn.net/home/hlwang/code/mujoco_warp/contrib/~/.conda/envs/mjwarp/lib/python3.12/site-packages/brax/training/acting.py:133) eval_state = self._generate_eval_unroll(policy_params, unroll_key)
    134 eval_metrics = eval_state.info['eval_metrics']
    135 eval_metrics.active_episodes.block_until_ready()

    [... skipping hidden 5 frame]

File ~/.conda/envs/mjwarp/lib/python3.12/site-packages/jax/_src/interpreters/pxla.py:1305, in ExecuteReplicated.__call__(self, *args)
   1303   self._handle_token_bufs(result_token_bufs, sharded_runtime_token)
   1304 else:
-> [1305](https://vscode-remote+ssh-002dremote-002borcd-002dcompute.vscode-resource.vscode-cdn.net/home/hlwang/code/mujoco_warp/contrib/~/.conda/envs/mjwarp/lib/python3.12/site-packages/jax/_src/interpreters/pxla.py:1305)   results = self.xla_executable.execute_sharded(input_bufs)
   1307 if dispatch.needs_check_special():
   1308   out_arrays = results.disassemble_into_single_device_arrays()

XlaRuntimeError: INTERNAL: CUDA error: Failed to create a child graph node and add it to a CUDA graph: CUDA_ERROR_NOT_SUPPORTED: operation not supported
```

The output log is below:

```
Module __main__ c862578 load on device 'cuda:0' took 6.56 ms  (cached)
Module mujoco_warp._src.smooth d3cee27 load on device 'cuda:0' took 7.78 ms  (cached)
Module mujoco_warp._src.collision_driver 8cab4e2 load on device 'cuda:0' took 9.20 ms  (cached)
Module mujoco_warp._src.collision_primitive ab9809c load on device 'cuda:0' took 8.14 ms  (cached)
Module mujoco_warp._src.constraint efb8bc3 load on device 'cuda:0' took 9.90 ms  (cached)
Module mujoco_warp._src.forward 1d77ebf load on device 'cuda:0' took 11.36 ms  (cached)
Module mujoco_warp._src.forward._actuator_velocity f9919fc load on device 'cuda:0' took 7.82 ms  (cached)
Module mujoco_warp._src.passive a3dddd0 load on device 'cuda:0' took 8.79 ms  (cached)
Module mujoco_warp._src.forward 4f4404b load on device 'cuda:0' took 8.79 ms  (cached)
Module mujoco_warp._src.forward dc75fe3 load on device 'cuda:0' took 9.83 ms  (cached)
Module mujoco_warp._src.support f63f4c0 load on device 'cuda:0' took 8.41 ms  (cached)
Module mujoco_warp._src.smooth._tile_cholesky_factorize_solve 7d8f9cc load on device 'cuda:0' took 61.65 ms  (cached)
Module mujoco_warp._src.solver b92e91c load on device 'cuda:0' took 10.24 ms  (cached)
Module mujoco_warp._src.support.mul_m_dense adcfbf7 load on device 'cuda:0' took 37.92 ms  (cached)
Module mujoco_warp._src.solver.update_gradient_cholesky 2cdcf5a load on device 'cuda:0' took 49.87 ms  (cached)
Module mujoco_warp._src.solver.linesearch_jv_fused a9dba30 load on device 'cuda:0' took 4.86 ms  (cached)
Module mujoco_warp._src.forward._tile_euler_dense 8643623 load on device 'cuda:0' took 54.56 ms  (cached)
E0727 22:45:55.194440  338069 pjrt_stream_executor_client.cc:2939] Execution of replica 0 failed: INTERNAL: CUDA error: Failed to create a child graph node and add it to a CUDA graph: CUDA_ERROR_NOT_SUPPORTED: operation not supported
```

I'm on the latest warp and mujoco:

```
warp: '1.9.0.dev20250727'
mujoco: '3.3.5'
```

**Comment by ellontop1** [comment]
Also facing this same issue, worked for me when I ran the Apptronik notebook example but when trying to bring a new embodiment I get the same error.

**Comment by juju0111** [comment]
[https://github.com/google-deepmind/mujoco_warp/issues/548](url)

Refer to the link!

**Comment by HaoliangWang** [comment]
Thanks for the reference! But it didn't work for me, this time it ran longer (~30min) before throwing out an error message:

```
Warp CUDA error 900: operation not permitted when stream is capturing (in function wp_cuda_unload_module, [/builds/omniverse/warp/warp/native/warp.cu:3960](/builds/omniverse/warp/warp/native/warp.cu:3960))
E external/xla/xla/stream_executor/cuda/cuda_command_buffer.cc:787] CUDA error: Failed to destroy CUDA graph: CUDA_ERROR_INVALID_VALUE: invalid argument
pjrt_stream_executor_client.cc:2939] Execution of replica 0 failed: INTERNAL: CUDA error: Failed to end stream capture: CUDA_ERROR_STREAM_CAPTURE_INVALIDATED: operation failed due to a previous error during capture
```

The full error message is:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[5], [line 71](vscode-notebook-cell:?execution_count=5&line=71)
     62 train_fn = functools.partial(
     63   ppo.train,
     64   **dict(ppo_training_params),
     65   network_factory=network_factory,
     66   progress_fn=progress,
     67 )
     69 env = Joystick()
---> [71](vscode-notebook-cell:?execution_count=5&line=71) make_inference_fn, params, metrics = train_fn(
     72   environment=env,
     73   wrap_env_fn=wrapper.wrap_for_brax_training,
     74 )
     76 print(f"time to jit: {times[1] - times[0]}")
     77 print(f"time to train: {times[-1] - times[1]}")

File ~/.conda/envs/mjwarp/lib/python3.12/site-packages/brax/training/agents/ppo/train.py:738, in train(environment, num_timesteps, max_devices_per_host, wrap_env, madrona_backend, augment_pixels, num_envs, episode_length, action_repeat, wrap_env_fn, randomization_fn, learning_rate, entropy_cost, discounting, unroll_length, batch_size, num_minibatches, num_updates_per_batch, num_resets_per_eval, normalize_observations, reward_scaling, clipping_epsilon, gae_lambda, max_grad_norm, normalize_advantage, network_factory, seed, num_evals, eval_env, num_eval_envs, deterministic_eval, log_training_metrics, training_metrics_steps, progress_fn, policy_params_fn, save_checkpoint_path, restore_checkpoint_path, restore_params, restore_value_fn, run_evals)
    736 metrics = training_metrics
    737 if run_evals:
--> [738](~/.conda/envs/mjwarp/lib/python3.12/site-packages/brax/training/agents/ppo/train.py:738)   metrics = evaluator.run_evaluation(
    739       params,
    740       training_metrics,
    741   )
    742 logging.info(metrics)
    743 progress_fn(current_step, metrics)

File ~/.conda/envs/mjwarp/lib/python3.12/site-packages/brax/training/acting.py:133, in Evaluator.run_evaluation(self, policy_params, training_metrics, aggregate_episodes)
    130 self._key, unroll_key = jax.random.split(self._key)
    132 t = time.time()
--> [133](~/.conda/envs/mjwarp/lib/python3.12/site-packages/brax/training/acting.py:133) eval_state = self._generate_eval_unroll(policy_params, unroll_key)
    134 eval_metrics = eval_state.info['eval_metrics']
    135 eval_metrics.active_episodes.block_until_ready()

ValueError: INTERNAL: CUDA error: Failed to end stream capture: CUDA_ERROR_STREAM_CAPTURE_INVALIDATED: operation failed due to a previous error during capture
```

**Comment by youwyu** [comment]
I found the following two changes will temporarily fix the issue.
` m.opt.graph_conditional = False`

```
..... = ffi.jax_callable(
      .....,
      graph_mode=ffi.GraphMode.WARP,
    )
```

**Comment by erikfrey** [comment]
I'm closing this in order to make a new issue which is simply to decide what kind of colabs we want as part of our official MJWarp release.  We may, for example, have a colab that introduces the user from basic concepts like forward / step, all the way up to training, or we may just point them to an external resource like mjlab, we will discuss this soon.
